//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.02 at 12:49:59 PM IST 
//


package in.gov.uidai.kyc.uid_kyc_response._2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the in.gov.uidai.kyc.uid_kyc_response._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _KycRes_QNAME = new QName("http://www.uidai.gov.in/kyc/uid-kyc-response/2.5", "KycRes");
    private final static QName _Resp_QNAME = new QName("http://www.uidai.gov.in/kyc/uid-kyc-response/2.5", "Resp");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: in.gov.uidai.kyc.uid_kyc_response._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KycRes }
     * 
     */
    public KycRes createKycRes() {
        return new KycRes();
    }

    /**
     * Create an instance of {@link Resp }
     * 
     */
    public Resp createResp() {
        return new Resp();
    }

    /**
     * Create an instance of {@link UidDataType }
     * 
     */
    public UidDataType createUidDataType() {
        return new UidDataType();
    }

    /**
     * Create an instance of {@link PrnType }
     * 
     */
    public PrnType createPrnType() {
        return new PrnType();
    }

    /**
     * Create an instance of {@link PoiType }
     * 
     */
    public PoiType createPoiType() {
        return new PoiType();
    }

    /**
     * Create an instance of {@link PoaType }
     * 
     */
    public PoaType createPoaType() {
        return new PoaType();
    }

    /**
     * Create an instance of {@link LDataType }
     * 
     */
    public LDataType createLDataType() {
        return new LDataType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KycRes }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link KycRes }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.uidai.gov.in/kyc/uid-kyc-response/2.5", name = "KycRes")
    public JAXBElement<KycRes> createKycRes(KycRes value) {
        return new JAXBElement<KycRes>(_KycRes_QNAME, KycRes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Resp }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Resp }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.uidai.gov.in/kyc/uid-kyc-response/2.5", name = "Resp")
    public JAXBElement<Resp> createResp(Resp value) {
        return new JAXBElement<Resp>(_Resp_QNAME, Resp.class, null, value);
    }

}
