//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.02 at 12:49:59 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.uidai.gov.in/authentication/uid-auth-request/2.5", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package in.gov.uidai.authentication.uid_auth_request._2;
