//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.02 at 12:49:59 PM IST 
//


package in.gov.uidai.kyc.uid_kyc_request._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import in.gov.uidai.kyc.common.types._2.YesNoType;


/**
 * <p>Java class for Kyc complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Kyc"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Rad" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ver" use="required" type="{http://www.uidai.gov.in/kyc/common/types/2.5}Ver" /&gt;
 *       &lt;attribute name="ts" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *       &lt;attribute name="ra" use="required" type="{http://www.uidai.gov.in/kyc/uid-kyc-request/2.5}raType" /&gt;
 *       &lt;attribute name="rc" use="required" type="{http://www.uidai.gov.in/kyc/common/types/2.5}YesNoType" /&gt;
 *       &lt;attribute name="mec" type="{http://www.uidai.gov.in/kyc/common/types/2.5}YesNoType" /&gt;
 *       &lt;attribute name="lr" type="{http://www.uidai.gov.in/kyc/common/types/2.5}YesNoType" /&gt;
 *       &lt;attribute name="de" type="{http://www.uidai.gov.in/kyc/common/types/2.5}YesNoType" /&gt;
 *       &lt;attribute name="pfr" type="{http://www.uidai.gov.in/kyc/common/types/2.5}YesNoType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Kyc", propOrder = {
    "rad"
})
public class Kyc {

    @XmlElement(name = "Rad", required = true)
    protected byte[] rad;
    @XmlAttribute(name = "ver", required = true)
    protected String ver;
    @XmlAttribute(name = "ts", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar ts;
    @XmlAttribute(name = "ra", required = true)
    protected RaType ra;
    @XmlAttribute(name = "rc", required = true)
    protected YesNoType rc;
    @XmlAttribute(name = "mec")
    protected YesNoType mec;
    @XmlAttribute(name = "lr")
    protected YesNoType lr;
    @XmlAttribute(name = "de")
    protected YesNoType de;
    @XmlAttribute(name = "pfr")
    protected YesNoType pfr;

    /**
     * Gets the value of the rad property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRad() {
        return rad;
    }

    /**
     * Sets the value of the rad property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setRad(byte[] value) {
        this.rad = value;
    }

    /**
     * Gets the value of the ver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVer() {
        return ver;
    }

    /**
     * Sets the value of the ver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVer(String value) {
        this.ver = value;
    }

    /**
     * Gets the value of the ts property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTs() {
        return ts;
    }

    /**
     * Sets the value of the ts property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTs(XMLGregorianCalendar value) {
        this.ts = value;
    }

    /**
     * Gets the value of the ra property.
     * 
     * @return
     *     possible object is
     *     {@link RaType }
     *     
     */
    public RaType getRa() {
        return ra;
    }

    /**
     * Sets the value of the ra property.
     * 
     * @param value
     *     allowed object is
     *     {@link RaType }
     *     
     */
    public void setRa(RaType value) {
        this.ra = value;
    }

    /**
     * Gets the value of the rc property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getRc() {
        return rc;
    }

    /**
     * Sets the value of the rc property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setRc(YesNoType value) {
        this.rc = value;
    }

    /**
     * Gets the value of the mec property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getMec() {
        return mec;
    }

    /**
     * Sets the value of the mec property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setMec(YesNoType value) {
        this.mec = value;
    }

    /**
     * Gets the value of the lr property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getLr() {
        return lr;
    }

    /**
     * Sets the value of the lr property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setLr(YesNoType value) {
        this.lr = value;
    }

    /**
     * Gets the value of the de property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getDe() {
        return de;
    }

    /**
     * Sets the value of the de property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setDe(YesNoType value) {
        this.de = value;
    }

    /**
     * Gets the value of the pfr property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getPfr() {
        return pfr;
    }

    /**
     * Sets the value of the pfr property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setPfr(YesNoType value) {
        this.pfr = value;
    }

}
